export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'

export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL'

export const UPVOTE_POST_REQUEST = 'UPVOTE_POST_REQUEST'
export const UPVOTE_POST_SUCCESS = 'UPVOTE_POST_SUCCESS'
export const UPVOTE_POST_FAIL = 'UPVOTE_POST_FAIL'

export const DOWNVOTE_POST_REQUEST = 'DOWNVOTE_POST_REQUEST'
export const DOWNVOTE_POST_SUCCESS = 'DOWNVOTE_POST_SUCCESS'
export const DOWNVOTE_POST_FAIL = 'DOWNVOTE_POST_FAIL'

export const COMMENT_POST_REQUEST = 'COMMENT_POST_REQUEST'
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS'
export const COMMENT_POST_FAIL = 'COMMENT_POST_FAIL'

export const SAVE_POST_REQUEST = 'SAVE_POST_REQUEST'
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS'
export const SAVE_POST_FAIL = 'SAVE_POST_FAIL'

export const UNSAVE_POST_REQUEST = 'UNSAVE_POST_REQUEST'
export const UNSAVE_POST_SUCCESS = 'UNSAVE_POST_SUCCESS'
export const UNSAVE_POST_FAIL = 'UNSAVE_POST_FAIL'

export const GET_SAVED_POSTS_REQUEST = 'GET_SAVED_POSTS_REQUEST'
export const GET_SAVED_POSTS_SUCCESS = 'GET_SAVED_POSTS_SUCCESS'
export const GET_SAVED_POSTS_FAIL = 'GET_SAVED_POSTS_FAIL'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'