export const CREATE_REPORT_REQUEST = 'CREATE_REPORT_REQUEST'
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS'
export const CREATE_REPORT_FAIL = 'CREATE_REPORT_FAIL'

export const GET_REPORTS_REQUEST = 'GET_REPORTS_REQUEST'
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS'
export const GET_REPORTS_FAIL = 'GET_REPORTS_FAIL'

export const BLOCK_USER_REQUEST = 'BLOCK_USER_REQUEST'
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS'
export const BLOCK_USER_FAIL = 'BLOCK_USER_FAIL'

export const IGNORE_REPORT_REQUEST = 'IGNORE_REPORT_REQUEST'
export const IGNORE_REPORT_SUCCESS = 'IGNORE_REPORT_SUCCESS'
export const IGNORE_REPORT_FAIL = 'IGNORE_REPORT_FAIL'

export const DELETE_REPORT_REQUEST = 'DELETE_REPORT_REQUEST'
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS'
export const DELETE_REPORT_FAIL = 'DELETE_REPORT_FAIL'