export const SUB_REGISTER_REQUEST = 'SUB_REGISTER_REQUEST'
export const SUB_REGISTER_SUCCESS = 'SUB_REGISTER_SUCCESS'
export const SUB_REGISTER_FAIL = 'SUB_REGISTER_FAIL'

export const MY_SUBS_GET_REQUEST = 'MY_SUBS_GET_REQUEST'
export const MY_SUBS_GET_SUCCESS = 'MY_SUBS_GET_SUCCESS'
export const MY_SUBS_GET_FAIL = 'MY_SUBS_GET_FAIL'

export const SUB_DELETE_REQUEST = 'SUB_DELETE_REQUEST'
export const SUB_DELETE_SUCCESS = 'SUB_DELETE_SUCCESS'
export const SUB_DELETE_FAIL = 'SUB_DELETE_FAIL'

export const SUBS_GET_REQUEST = 'SUBS_GET_REQUEST'
export const SUBS_GET_SUCCESS = 'SUBS_GET_SUCCESS'
export const SUBS_GET_FAIL = 'SUBS_GET_FAIL'

export const ONE_SUB_GET_REQUEST = 'ONE_SUB_GET_REQUEST'
export const ONE_SUB_GET_SUCCESS = 'ONE_SUB_GET_SUCCESS'
export const ONE_SUB_GET_FAIL = 'ONE_SUB_GET_FAIL'

export const SUB_REQUEST_FOLLOW_REQUEST = 'SUB_JOIN_REQUEST'
export const SUB_REQUEST_FOLLOW_SUCCESS = 'SUB_JOIN_SUCCESS'
export const SUB_REQUEST_FOLLOW_FAIL = 'SUB_JOIN_FAIL'

export const SUB_ACCEPT_FOLLOW_REQUEST = 'SUB_ACCEPT_FOLLOW_REQUEST'
export const SUB_ACCEPT_FOLLOW_SUCCESS = 'SUB_ACCEPT_FOLLOW_SUCCESS'
export const SUB_ACCEPT_FOLLOW_FAIL = 'SUB_ACCEPT_FOLLOW_FAIL'

export const GET_NUM_POSTS_REQUEST = 'GET_NUM_POSTS_REQUEST'
export const GET_NUM_POSTS_SUCCESS = 'GET_NUM_POSTS_SUCCESS'
export const GET_NUM_POSTS_FAIL = 'GET_NUM_POSTS_FAIL'

export const SUB_LEAVE_REQUEST = 'SUB_LEAVE_REQUEST'
export const SUB_LEAVE_SUCCESS = 'SUB_LEAVE_SUCCESS'
export const SUB_LEAVE_FAIL = 'SUB_LEAVE_FAIL'

export const REJECT_FOLLOW_REQUEST = 'REJECT_FOLLOW_REQUEST'
export const REJECT_FOLLOW_SUCCESS = 'REJECT_FOLLOW_SUCCESS'
export const REJECT_FOLLOW_FAIL = 'REJECT_FOLLOW_FAIL'
