export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

export const GET_AUTHOR_REQUEST = 'GET_AUTHOR_REQUEST'
export const GET_AUTHOR_SUCCESS = 'GET_AUTHOR_SUCCESS'
export const GET_AUTHOR_FAIL = 'GET_AUTHOR_FAIL'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'

export const GET_FOLLOWERS_REQUEST = 'GET_FOLLOWERS_REQUEST'
export const GET_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS'
export const GET_FOLLOWERS_FAIL = 'GET_FOLLOWERS_FAIL'

export const GET_FOLLOWING_REQUEST = 'GET_FOLLOWING_REQUEST'
export const GET_FOLLOWING_SUCCESS = 'GET_FOLLOWING_SUCCESS'
export const GET_FOLLOWING_FAIL = 'GET_FOLLOWING_FAIL'

export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST'
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS'
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL'

export const USER_REMOVE_FOLLOWER_REQUEST = 'USER_REMOVE_FOLLOWER_REQUEST'
export const USER_REMOVE_FOLLOWER_SUCCESS = 'USER_REMOVE_FOLLOWER_SUCCESS'
export const USER_REMOVE_FOLLOWER_FAIL = 'USER_REMOVE_FOLLOWER_FAIL'

export const USER_UNFOLLOW_REQUEST = 'USER_UNFOLLOW_REQUEST'
export const USER_UNFOLLOW_SUCCESS = 'USER_UNFOLLOW_SUCCESS'
export const USER_UNFOLLOW_FAIL = 'USER_UNFOLLOW_FAIL'

export const GET_BANNED_USERS_REQUEST = 'GET_BANNED_USERS_REQUEST'
export const GET_BANNED_USERS_SUCCESS = 'GET_BANNED_USERS_SUCCESS'
export const GET_BANNED_USERS_FAIL = 'GET_BANNED_USERS_FAIL'